# Generated by Django 4.2.10 on 2024-02-18 09:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('annual_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instalment_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('custom', 'Custom')], max_length=20)),
                ('start_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'In progress'), (1, 'Completed'), (2, 'Due')], default=0)),
                ('payment_mode', models.CharField(max_length=20)),
                ('staff_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareholder.shareholder')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInstalment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.IntegerField(choices=[(0, 'In progress'), (1, 'Completed'), (2, 'Due')], default=0)),
                ('paid_at', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareholder.sharepayment')),
            ],
        ),
    ]
